#!/usr/bin/env bash
# configures nginx to run and listen to port 80

rm /etc/nginx/sites-enabled/default
#configure nginx
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
#restart nginx
service nginx restart
