#!/usr/bin/env bash
# Changes port in Nginx
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
#restart nginx
sudo service nginx restart
#terminate first nginx
kill "$(pgrep 'nginx' | head -1)"
